# For more info on HTTP files go to https://aka.ms/vs/httpfile

@schema=https
@hostname=localhost
@port=7211

GET {{schema}}://{{hostname}}:{{port}}/api/cities

###
GET {{schema}}://{{hostname}}:{{port}}/api/cities/2
Accept:application/xml

###
GET {{schema}}://{{hostname}}:{{port}}/api/cities/1
Accept:application/json