name: File Action
on: workflow_dispatch
jobs: 
  file-action-job:
    runs-on: ubuntu-latest
    steps:
      - uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.md'
          search-text: 'version'
          replacement-text: '42'
      - name: Replace single file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'README.md'
          search-text: 'Hello'
          replacement-text: 'dlam'
          
