name: File Action
on: workflow_dispatch
jobs: 
  file-action-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace string in file
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: README.md
          old-string: version
          new-string: ${{ dlam }}
          
