name: Second Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: bluwy/substitute-string-action@v3
        id: sub
        with:
          _input-text: 'Hello World!'
          World: GitHub
      - run: echo ${{ steps.sub.outputs.result }} # Prints 'Hello GitHub!'
